<?php $productId = $this->getProduct()->getId(); ?>
<?php $useAjax = $this->helper('dpi')->getStoreConfig(DV_DPI_Helper_Data::XML_PATH_USE_AJAX); ?>
<?php $useModal = $this->helper('dpi')->getStoreConfig(DV_DPI_Helper_Data::XML_PATH_USE_MODAL); ?>
<?php $storeId = Mage::app()->getStore()->getId(); ?>
<?php if(($attributes = $this->getAttributesList($productId)) && $this->helper('dpi')->getStoreConfig(DV_DPI_Helper_Data::XML_PATH_ENABLED)):?>
    <li>
        <span class="separator">|</span>
        <a id="<?php echo 'attr-'.$productId; ?>" class="show-attribute link-compare <?php if($useModal): echo 'dpi-modal" '; else: echo 'dpi-toggle" '; endif; ?> onclick="return false;"  href="<?php echo $this->getUrl('dpi/attribute/index?id='.$productId.'&ajax='.$useAjax.'&modal='.$useModal.'&store='.$storeId); ?>" title="<?php echo $this->__("Detailed Info");?>"><?php echo $this->__("Detailed Info");?></a>
    </li>
    <?php if(!$useAjax):?>
        <ul class="attr-wrapper">
            <li id="product-attr-<?php echo $productId; ?>" class="attr-table" style="display: none; ">
                <table class="data-table">
                    <?php $iterator = 0; ?>
                    <?php foreach ($attributes as $label => $html): ?>
                        <?php if(!is_array($html)): ?>
                            <tr <?php if($iterator % 2 == 0): echo 'class="odd"'; else: echo 'class="even"'; endif; $iterator++;?>>
                                <th class="label"><?php echo $label; ?></th>
                                <td class="data"><?php echo nl2br($html, true); ?></td>
                            </tr>
                        <?php endif;?>
                    <?php endforeach; ?>
                </table>
            </li>
        </ul>
    <?php endif; ?>
<?php endif; ?>
