<div id="<?php echo $this->getHtmlId() ?>">
    <table cellspacing="0" cellpadding="0" class="massaction">
        <tr>
            <td>
                <a href="#" class="attr-select" onclick="return false; "><?php echo $this->__('Select Visible') ?></a>
                <span class="separator">|</span>
                <a href="#" class="attr-unselect" onclick="return false "><?php echo $this->__('Unselect Visible') ?></a>
                <span class="separator">|</span>
            </td>
        </tr>
    </table>
</div>

